CREATE TABLE Fahrzeug_DIMENSION (
    FZ_DIM_ID INT IDENTITY(1,1) PRIMARY KEY,
    FZ_ID VARCHAR(50),
	FZ_NUTZER_ID VARCHAR(50),
    SCHADSTOFFKLASSE VARCHAR(20),
    ACHSEN INT,
    MAUTKATEGORIE VARCHAR(5),
    GEWICHT DECIMAL(15,2),
    MAUSATZ DECIMAL(15,2),
    FIN VARCHAR(50),
    KENNZEICHEN VARCHAR(20)
);
