USE [u575710]; -- Ersetze dies durch den Namen deiner Datenbank
GO

CREATE PROCEDURE Update_Fahrzeug_DIMENSION
    @FZ_ID VARCHAR(50),
	@FZ_NUTZER_ID VARCHAR(50),
    @SCHADSTOFFKLASSE VARCHAR(20),
    @ACHSEN INT,
    @MAUTKATEGORIE VARCHAR(5),
    @GEWICHT DECIMAL(15,2),
    @MAUSATZ DECIMAL(15,2),
    @FIN VARCHAR(50),
    @KENNZEICHEN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    -- Update-Anweisung
    UPDATE Fahrzeug_DIMENSION
    SET 
        FZ_NUTZER_ID = @FZ_NUTZER_ID,
        SCHADSTOFFKLASSE = @SCHADSTOFFKLASSE,
        ACHSEN = @ACHSEN,
		MAUTKATEGORIE = @MAUTKATEGORIE,
		GEWICHT = @GEWICHT,
		MAUSATZ = @MAUSATZ,
		FIN = @FIN,
		KENNZEICHEN = @KENNZEICHEN
    WHERE 
        FZ_ID = @FZ_ID;
END
GO