CREATE TABLE Nutzer_DIMENSION (
    NUTZER_DIM_ID INT IDENTITY(1,1) PRIMARY KEY,
    NUTZER_ID VARCHAR(50),
    FIRMENNAME VARCHAR(100),
    VORNAME VARCHAR(50),
    NACHNAME VARCHAR(50),
    LAND VARCHAR(50),
    STRASSE VARCHAR(50),
    HAUSNUMMER VARCHAR(5),
    PLZ VARCHAR(20)
);
